In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data_set=pd.read_csv("train.tsv",delimiter="\t",quoting=3)

In [4]:
data_set

id  label                                              tweet
0          1      0  @user when a father is dysfunctional and is so...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?😍😍😍😍😍ð...
31958  31959      0  to see nina turner on the airwaves trying to w...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                     thank you @user for you follow

[31962 rows x 3 columns]

In [5]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
corpus=[]

for i in range(len(data_set)):
    corona_review=re.sub('[^a-zA-Z]',' ',data_set["tweet"][i])
    corona_review=re.sub('https',' ',corona_review)
    corona_review=corona_review.lower()
    corona_review=corona_review.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words("english")
    all_stopwords.remove("not")
    corona_review=[ps.stem(word) for word in corona_review if not word in set(all_stopwords)]
    corona_review=' '.join(corona_review)
    corpus.append(corona_review)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1600)
x=cv.fit_transform(corpus).toarray()
y=data_set.iloc[:,1].values

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

## Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression
log_classifier=LogisticRegression()
log_classifier.fit(x_train,y_train)

LogisticRegression()

In [10]:
log_classifier.score(x_train,y_train)

0.9609292502639916

In [11]:
log_classifier.score(x_test,y_test)

0.9497888315344909

In [12]:
y_train_pred=log_classifier.predict(x_train)
y_test_pred=log_classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
print("Train Confusion Matrix\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix\n",confusion_matrix(y_test,y_test_pred))

Train Confusion Matrix
 [[23665   118]
 [  881   905]]
Test Confusion Matrix
 [[5872   65]
 [ 256  200]]


## KNN

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier(metric="minkowski",p=2)
knn_classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [14]:
knn_classifier.score(x_train,y_train)

0.9542805741327388

In [15]:
knn_classifier.score(x_test,y_test)

0.9424370405130612

In [16]:
y_train_pred=knn_classifier.predict(x_train)
y_test_pred=knn_classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
print("Train Confusion Matrix\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix\n",confusion_matrix(y_test,y_test_pred))

Train Confusion Matrix
 [[23714    69]
 [ 1100   686]]
Test Confusion Matrix
 [[5914   23]
 [ 345  111]]
