In [1]:
import numpy as np
import pandas as pd

In [2]:
data_set=pd.read_csv("spam_ham_dataset.csv")
data_set.head(5)

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [3]:
data_set.isna().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [4]:
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

In [11]:
corpus=[]

for i in range(len(data_set)):
    spam_check=re.sub("[^a-zA-Z]",' ',data_set["text"][i])
    # spam_check=re.sub("[subject]",' ',spam_check)
    spam_check=spam_check.lower()
    spam_check=spam_check.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words("english")
    all_stopwords.remove("not")
    spam_check=[ps.stem(word) for word in spam_check if not word in set(all_stopwords)]
    spam_check=' '.join(spam_check)
    corpus.append(spam_check)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1600)
x=cv.fit_transform(corpus).toarray()
y=data_set.iloc[:,-1].values

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

## Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
log_classifier=LogisticRegression()
log_classifier.fit(x_train,y_train)

LogisticRegression()

In [22]:
log_classifier.score(x_train,y_train)

0.9959166129378896

In [23]:
log_classifier.score(x_test,y_test)

0.972972972972973

In [24]:
y_train_pred=log_classifier.predict(x_train)
y_test_pred=log_classifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix of Train:\n",confusion_matrix(y_train,y_train_pred))
print("Confusion Matrix of Test:\n",confusion_matrix(y_test,y_test_pred))

Confusion Matrix of Train:
 [[3283   18]
 [   1 1351]]
Confusion Matrix of Test:
 [[361  10]
 [  4 143]]


## SVC

In [26]:
from sklearn.svm import SVC
svc_classifier=SVC(kernel="rbf",random_state=42)
svc_classifier.fit(x_train,y_train)

SVC(random_state=42)

In [27]:
svc_classifier.score(x_train,y_train)

0.968407479045777

In [28]:
svc_classifier.score(x_test,y_test)

0.9536679536679536

In [30]:
y_train_pred=svc_classifier.predict(x_train)
y_test_pred=svc_classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
print("Train Confusion Matrix:\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,y_test_pred))

Train Confusion Matrix:
 [[3163  138]
 [   9 1343]]
Test Confusion Matrix:
 [[352  19]
 [  5 142]]


## KNN

In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier(metric="minkowski",p=2)
knn_classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [32]:
print("Train Score:",svc_classifier.score(x_train,y_train))
print("Test Score:",svc_classifier.score(x_test,y_test))

Train Score: 0.968407479045777
Test Score: 0.9536679536679536


In [33]:
y_train_pred=knn_classifier.predict(x_train)
y_test_pred=knn_classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
print("Train Confusion Matrix:\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,y_test_pred))

Train Confusion Matrix:
 [[2908  393]
 [  21 1331]]
Test Confusion Matrix:
 [[304  67]
 [  7 140]]


## Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier(criterion="entropy",random_state=42)
tree_classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [36]:
print("Train Score:",tree_classifier.score(x_train,y_train))
print("Test Score:",tree_classifier.score(x_test,y_test))

Train Score: 0.9993552546744036
Test Score: 0.9401544401544402


In [37]:
y_train_pred=tree_classifier.predict(x_train)
y_test_pred=tree_classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
print("Train Confusion Matrix:\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,y_test_pred))

Train Confusion Matrix:
 [[3298    3]
 [   0 1352]]
Test Confusion Matrix:
 [[353  18]
 [ 13 134]]


## ANN

In [38]:
from keras.layers import Dense
from keras.models import Sequential

In [39]:
model=Sequential()
model.add(Dense(units=50,activation="relu",input_shape=x_train.shape))
model.add(Dense(units=20,activation="relu"))
model.add(Dense(units=1,activation="sigmoid"))
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [40]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
146/146 [==============================] - 2s 2ms/step - loss: 0.2490 - accuracy: 0.8960
Epoch 2/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0554 - accuracy: 0.9871
Epoch 3/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0259 - accuracy: 0.9914
Epoch 4/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0147 - accuracy: 0.9966
Epoch 5/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0094 - accuracy: 0.9983
Epoch 6/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 0.9987
Epoch 7/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0049 - accuracy: 0.9994
Epoch 8/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 0.9994
Epoch 9/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.9994
Epoch 10/20
146/146 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9994

In [49]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [51]:
y_train_pred=(y_train_pred>0.5)
y_test_pred=(y_test_pred>0.5)

In [52]:
y_train_pred=np.multiply(y_train_pred,1)
y_test_pred=np.multiply(y_test_pred,1)

In [60]:
from sklearn.metrics import accuracy_score,confusion_matrix

print("Train Accuracy Score:",accuracy_score(y_train,y_train_pred))
print("Test Accuracy Score:",accuracy_score(y_test,y_test_pred))

print("Train Confusion Matrix:\n",confusion_matrix(y_train,y_train_pred))
print("Test Confusion Matrix:\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy Score: 0.9993552546744036
Test Accuracy Score: 0.974903474903475
Train Confusion Matrix:
 [[3298    3]
 [   0 1352]]
Test Confusion Matrix:
 [[367   4]
 [  9 138]]


## Testing a random data

In [77]:
test='Subject: re : tenaska iv 10 / 00'
test_corpus=[]

test_check=re.sub("[^a-zA-Z]",' ',test)
test_check=test_check.lower()
test_check=test_check.split()
ps=PorterStemmer()
all_stopwords=stopwords.words("english")
all_stopwords.remove("not")
test_check=[ps.stem(word) for word in test_check if not word in set(all_stopwords)]
test_check=' '.join(test_check)
test_corpus.append(test_check)

In [78]:
test=cv.transform(test_corpus).toarray()
predict=model.predict(test)

np.multiply((predict>0.5),1)

array([[0]])